# Generated by Django 2.2.2 on 2019-06-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
